export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const FILTER_RESTAURANTS = "FILTER_RESTAURANTS";
export const FETCH_RESTAURANT_BY_ID = "FETCH_RESTAURANT_BY_ID";
export const SET_NAME = "SET_NAME";
export const SET_SORTBY = "SET_SORTBY";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const SET_TOTAL_PRICE = "SET_TOTAL_PRICE";
